### PR TITLE
Add pallet gilt

### PR DESCRIPTION
**Pull request by zycon91**
Added `pallet-gilt` in our runtime

### CODE REVIEW

**Comment by charmitro** [comment]
Will a runtime upgrade be sufficient? Did you test a runtime upgrade beforehand? @zycon91

**Comment by zycon91** [comment]
> Will a runtime upgrade be sufficient? Did you test a runtime upgrade beforehand? @zycon91

We added it to Testnet via a runtime upgrade. Things broke though after 300-350 blocks. I will try adding it in a local testnet before we proceed.

**Comment by charmitro** [comment]
> We added it to Testnet via a runtime upgrade. Things broke though after 300-350 blocks. I will try adding it in a local testnet before we proceed.

This repo is forked from Substrate therefore things should differ. Try a runtime upgrade and provide results.

**Comment by zycon91** [comment]
Unfortunately adding `pallet-gilt` through a runtime upgrade bricked the running chain. We are getting an error just before the `intake_duration` ends.

The error we are getting is the following:
```
2022-11-04 16:04:18 panicked at 'index out of bounds: the len is 0 but the index is 299', /Users/zycon/cherry/substrate/frame/gilt/src/lib.rs:600:28
2022-11-04 16:04:18 Proposing failed: Import failed: Error at calling runtime api: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed
WASM backtrace:

    0: 0x4a57eb - <unknown>!rust_begin_unwind
```

I have opened a [question](https://substrate.stackexchange.com/questions/5696/adding-pallet-gilt-to-a-running-chain-bricks-the-chain) in substrate stack exchange as well.

**Review by charmitro — COMMENTED** [review]
Did you test a runtime upgrade on a runtime that already has `Gilt` enabled? Our testnet already is already loaded with `Gilt`, therefore you must test it that way. 

If this doesn't work we must move forward with two runtime upgrades:
1. Removing `Gilt` from our runtime.
2. Adding `Gilt` again so the migration happen

**Comment by zycon91** [comment]
> Did you test a runtime upgrade on a runtime that already has `Gilt` enabled? Our testnet already is already loaded with `Gilt`, therefore you must test it that way.
> 
> If this doesn't work we must move forward with two runtime upgrades:
> 
> 1. Removing `Gilt` from our runtime.
> 2. Adding `Gilt` again so the migration happen

I can try that for sure. At the moment I am trying to add `pallet-gilt` through a runtime upgrade in a substrate-based chain (like Cherry-Node).

**Comment by charmitro** [comment]
> > Did you test a runtime upgrade on a runtime that already has `Gilt` enabled? Our testnet already is already loaded with `Gilt`, therefore you must test it that way.
> > If this doesn't work we must move forward with two runtime upgrades:
> > 
> > 1. Removing `Gilt` from our runtime.
> > 2. Adding `Gilt` again so the migration happen
> 
> I can try that for sure. At the moment I am trying to add `pallet-gilt` through a runtime upgrade in a substrate-based chain (like Cherry-Node).

Perfect. Re-request my review when needed! 🚀

**Comment by zycon91** [comment]
> 

We should be fine to merge. Inflation calculation fix worked perfectly locally and on Testnet.

**Review by charmitro — APPROVED** [review]

**Pull request merged**
