### PR TITLE
wip: voting "power" of council members.

### PR DESCRIPTION
**Pull request by zycon91**
Added voting "power" to council members. Each `GovToken` they hold, gives them 1 point/vote. I had to add the `set_gov_token_id` function to `pallet_council` aswell (couldn't find a way to read/take the `GovTokenId` otherwise).

~~I added a temporary storage showing the AccountId of the user and the voting "power" he possesses.~~

Added `yes_power` and `no_power` to the `Voting` storage.

### CODE REVIEW

**Comment by zycon91** [comment]
Should I add in the `yes_power` and `no_power` a vector containing vectors with `AccountId`, `voting_power` ? It might look better but I don't know if we need it.

Screenshot 2022-05-16 at 8 11 44 PM

**Comment by charmitro** [comment]
> Should I add in the `yes_power` and `no_power` a vector containing vectors with `AccountId`, `voting_power` ? It might look better but I don't know if we need it.
> 
> Screenshot 2022-05-16 at 8 11 44 PM

There's no need for that just yet.

**Comment by charmitro** [comment]
Discussion: We should find a way to completely remove the simple `yays`/`nays` and convert it to our so called `powers`.

**Comment by zycon91** [comment]
> 

was thinking about that, but they are used in weight calculations. Will see if I can come up with anything.

**Comment by charmitro** [comment]
> was thinking about that, but they are used in weight calculations. Will see if I can come up with anything.

What will happen to weights if we calculate them based on the `powers`?

**Comment by zycon91** [comment]
> > was thinking about that, but they are used in weight calculations. Will see if I can come up with anything.
> 
> What will happen to weights if we calculate them based on the `powers`?

Can check it out, but I suppose the weight will increase by a lot. Also, the `yays`/`nays` have the AccountID in them. It should be nice to have them, so that we know which node voted.

**Comment by charmitro** [comment]
> > > was thinking about that, but they are used in weight calculations. Will see if I can come up with anything.
> > 
> > 
> > What will happen to weights if we calculate them based on the `powers`?
> 
> Can check it out, but I suppose the weight will increase by a lot. Also, the `yays`/`nays` have the AccountID in them. It should be nice to have them, so that we know which node voted.

Okay, proceed with those changes.

**Comment by zycon91** [comment]
I think we are ready to merge that.

**Review by charmitro — APPROVED** [review]

**Comment by zycon91** [comment]
Closes #88 and #92

**Pull request merged**
